### ISSUE TITLE
Was this discontinued?

### ISSUE THREAD

**Issue by seantiz** [mw2000/linkedin-sync#3]
It would have been really great for this to still be up and running, but I tried it today and Obsidian fails to load the plugin when I toggle it in the plugins menu.

**Comment by rigzindorje** [comment]
Yes +1, same problem with 1.5.3 on Mac and LinkedIn Sync 0.1.1: "Failed to load plugin linkedin-sync"

**Comment by mw2000** [comment]
Hey guys! I haven't been actively maintaining/adding to it at the moment. Although, I did want to have a look at this soon. Feel free to create PRs if needed! More than happy to merge those in

**Comment by seantiz** [comment]
Hi @mw2000 @rigzindorje I've made that PR now, and the updated app does correctly load into Obsidian on my end now, where I can click connect and it opens the LinkedIn modal window.

I can't test it any further than that at the moment (as in I have no idea whether it successfully connects and posts to LinkedIn) because I de-activated the page associated with the app on my end. I've re-activated it today but it'll take a while for LinkedIn to let my page get up and running again.

Please let me know if it works on your end. Have a good weekend.
